# Auto Deploy to VPS

name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy App to VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/apps # go to app dir
            rm -rf js-calculator/ # wipe out app for fresh build
            git clone https://github.com/UnfocusedDrive/js-calculator.git # get latest
            cd js-calculator # go to app dir
            npm install # get latest packages
            npm run build # build app
            rm -rf /var/www/unstable.memoryleak.ai/js-calculator/ # remove dir
            mkdir /var/www/unstable.memoryleak.ai/js-calculator/ # rebuild dir
            sudo mv -i dist/* /var/www/unstable.memoryleak.ai/js-calculator/ # move build to serve dir
            echo 'Successfully deployed to unstable.memoryleak.ai/js-calculator/'
